spring.datasource.url=jdbc:postgresql://localhost:5433/finbridge
spring.datasource.username=billuser
spring.datasource.password=billpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true

aws.region=us-east-1
aws.endpoint-override=http://localhost:4566

s3.default-bucket=bill-manager-local

logging.level.com.example.billmanager=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.software.amazon.awssdk=WARN