spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=false

aws.region=${AWS_REGION:us-east-1}

s3.default-bucket=${S3_BUCKET_NAME}

logging.level.com.example.billmanager=INFO
