spring.application.name=finbridge

spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
#spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
server.port=8080

camel.springboot.name=BillManagerContext
camel.springboot.main-run-controller=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

aws.region=us-east-1

logging.level.com.example.billmanager=DEBUG
logging.level.org.apache.camel=INFO
logging.level.org.flywaydb=INFO